apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rs5pxn4z9-go 
  janus-idp.io/tekton: rs5pxn4z9-go
  backstage.io/kubernetes-id: rs5pxn4z9-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rs5pxn4z9-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml