apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rs5pxn4z9-go
  janus-idp.io/tekton: rs5pxn4z9-go
  backstage.io/kubernetes-id: rs5pxn4z9-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rs5pxn4z9-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
